
const {connectMongo} = require("./dbConnection")
connectMongo("mongodb://mongo:CcAFfRcqtqhvOwAsAVtSTiKAmbpnUsql@yamabiko.proxy.rlwy.net:13180/pet-train-adop?authSource=admin")
const {userRouter} = require("./routers/user")
const { adminRouter } = require("./routers/admin")
const {trainingRouter} = require("./routers/training")
const {trainingAmountRouter} = require('./routers/trainingamount')
const {petDaysCareRouter} = require('./routers/petdayscare')
const {petDaysCareAmountRouter}=require('./routers/petdayscareamount')
const express= require("express")
const app = express()
const cors = require("cors")
const path = require("path")
const distFolder =path.join(__dirname,'../frontend/dist')
console.log(distFolder)
app.use(cors())
app.use(express.json())
app.use('/user',userRouter)
app.use('/admin',adminRouter)
app.use('/training',trainingRouter)
app.use('/trainingamount',trainingAmountRouter)
app.use('/petdayscare',petDaysCareRouter)
app.use('/petdayscareamount',petDaysCareAmountRouter)
app.use(express.static(distFolder))
app.get('*',(_,res)=>{
    res.sendFile(path.join(distFolder,'index.html'))
})
app.listen("5504",()=>{
    console.log("your port is running on 5504")
})